### docker build -f Dockerfile-node -t "node:9.4-react-scripts" ./ 

# base image
FROM node:9.4

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY ./package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@3.1.2 -g --silent
