# FROM python:3.8.0-alpine
FROM python:3.6.4

# install environment dependencies
RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
        netcat \
    && apt-get -q clean

# RUN apk update && \
#     apk add --virtual build-deps gcc python-dev musl-dev && \
#     apk add postgresql-dev && \
#     apk add netcat-openbsd



# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt .

# install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh .

# RUN chmod a+x entrypoint.sh
RUN chmod +x entrypoint.sh

# add app
COPY . /usr/src/app

# run server
# CMD ["./entrypoint.sh"]
CMD ["sh", "./entrypoint.sh"]
# ENTRYPOINT ["sh", "./entrypoint.sh"]
