# FROM python:3.8.0-alpine
FROM python:3.6.4

# # install environment dependencies
# RUN apt-get update -yqq \
#     && apt-get install -yqq --no-install-recommends \
#         netcat \
#     && apt-get -q clean

# ## To fix this just use:
# # apk update and apk add

# # RUN apk update
# # RUN apk add netcat


# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
# COPY ./requirements.txt /usr/src/app/requirements.txt
COPY ./requirements.txt .

# install requirements
RUN pip install -r requirements.txt

# # add entrypoint.sh
# COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

# run server
CMD python manage.py run -h 0.0.0.0
# CMD ["./entrypoint.sh"]
