FROM python:3.6.4

# install environment dependencies
RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
        netcat \
    && apt-get -q clean

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt .

# install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# add entrypoint-prod.sh
COPY ./entrypoint-prod.sh .

# RUN chmod a+x entrypoint-prod.sh
RUN chmod +x entrypoint-prod.sh

# add app
COPY . /usr/src/app

# run server
CMD ["sh", "./entrypoint-prod.sh"]
