# base image
# FROM node:9.4
FROM node:9.4-react-scripts
# FROM node:12-alpine

# set working directory
# RUN mkdir /usr/src/app
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY ./package.json /usr/src/app/package.json
RUN npm install --silent
# RUN npm install react-scripts@1.1.0 -g --silent
# RUN npm install react-scripts@3.1.2 -g --silent


# add app
# COPY . /usr/src/app

# start app
CMD ["npm", "start"]
